# Copyright (c) 2022, WSO2 Inc. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 Inc. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.

resources:
  repositories:
    - repository: common-templates
      type: github
      name: wso2-enterprise/choreo-common-pipeline-templates
      endpoint: choreo-cicd
  containers:
    - container: choreo-ballerina
      image: choreoanonymouspullable.azurecr.io/choreoipaas/choreo-ballerina:2201.0.5-azure-builder

trigger: none

pr:
  branches:
    include:
      - "*"

jobs:
  - job: build_test
    displayName: Build and Test
    pool:
      vmImage: "ubuntu-latest"
    container: choreo-ballerina
    steps:
      - template: templates/cp-choro-admin-api-test.yml
      - template: templates/cp-choro-admin-api-build.yml
  - job: docker_build
    displayName: Docker Build
    pool:
      vmImage: "ubuntu-latest"
    variables:
      CONTAINER_REGISTRY: choreocontrolplane.azurecr.io
      REPOSITORY: choreoipaas/choreo-admin-api-deployer
      TAG: $(Build.SourceBranchName)-$(Build.SourceVersion)
    steps:
      - task: Docker@2
        displayName: "Build Docker image"
        inputs:
          command: build
          containerRegistry: "wso2choreo-control-plane-acr"
          repository: $(REPOSITORY)
          tags: $(TAG)
          Dockerfile: "Dockerfile"
          buildContext: "."
      - template: templates/trivy-docker-scan.yml
        parameters:
          registry: $(CONTAINER_REGISTRY)
          repository: $(REPOSITORY)
          tag: $(TAG)
