# Copyright (c) 2022, WSO2 Inc. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 Inc. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.

resources:
  repositories:
    - repository: CHOREO_TEMPLATES
      type: github
      name: wso2-enterprise/choreo-common-pipeline-templates
      endpoint: choreo-cicd

trigger:
  batch: true
  branches:
    include:
      - refs/tags/v*

pr: none

jobs:
  - job: release_build
    displayName: Build/Test/DockerPush
    timeoutInMinutes: 120
    pool:
      vmImage: "ubuntu-latest"

    variables:
      CONTAINER_REGISTRY: choreocontrolplane.azurecr.io
      REPOSITORY: choreoipaas/choreo-admin-api
      TAG: $(Build.SourceBranchName)

    steps:
      - task: Docker@2
        displayName: "Build Docker image"
        inputs:
          command: build
          containerRegistry: "wso2choreo-control-plane-acr"
          repository: $(REPOSITORY)
          Dockerfile: "Dockerfile"
          buildContext: "."
          tags: $(TAG)
      - template: templates/trivy-docker-scan.yml
        parameters:
          repository: $(REPOSITORY)
          tag: $(TAG)
          registry: $(CONTAINER_REGISTRY)
      - task: Docker@2
        displayName: "Push Docker image"
        inputs:
          command: push
          containerRegistry: "wso2choreo-control-plane-acr"
          repository: $(REPOSITORY)
          tags: $(TAG)
